global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.IO;
global using System.Text;
global using System.Threading.Tasks;
global using SoundID = int;
global using StatusID = int;
global using XPScalingTableID = int;
global using ItemID = int;
global using ItemSetID = int;
global using PowerID = int;
